= Change 

Create Dataview out of the current view

== Goal of the activity

The user can navigate in the table view and we would like to be able a stored Dataview out of the current settings that the user has set within that Dataview

The filtering, the sorting and Freetext filtering shall be automatically acknowledged and stored. 

The name of the dataview shall be user-given.

The dataview shall be stored in an automatic Package specifically for that activity. 

The user shall be able to easily use that dataview. 

== Workpackage Breakdown

* [ ] Check that the user can filter and sort as intended
** [ ] Migrate Dataview to use Dynamic Views
* [ ] Activate Storage of the current view
** [ ] Provide Storage button
** [ ] By activation of the Storage button, the user shall be able to define the name of the created DataView
** [ ] Define package in which the user-defined storages shall be done
** [ ] Store current DataView into the defined Package
* [ ] Define Mechanism to retrieve the stored view
** [ ] Include Form Selector into the Table View
** [ ] User shall be able to select the DataView



=== Check that the user can filter and sort as intended
 
=== Activate Storage of the current view

==== Provide and define Storage button

==== Define package in which the user-defined storages shall be done

==== Store current DataView into the defined Package

The defined dataview shall contain a dynamic mechanism which allows also the use of the DataView for other tables

=== Define Mechanism to retrieve the stored view

==== Include Form Selector into the Table View