= Actions and Action Sets

Through actions, the user of the Datenmeister can define a sequence of activities that are executable in the DatenMeister context.

For this purpose, there are two base classes:
. Action
. ActionSet

Each action has the following properties:

[%header,cols="1,5"]
|===
|Name|Description
|name|Name of the action
|isDisabled|Flag indicating whether the action is disabled and thus skipped in the action collection.
|===

== ActionSet

An ActionSet (action collection) collects various actions.

[%header,cols="1,5"]
|===
|Name|Description
|name|Name of the action collection
|===
== Action

The base class Action represents an action. However, this class must be derived to concretize the action.


[%header,cols="1,5"]
|===
|Name|Description
|name|Name of the action
|===

== LoggingWriterAction

Writes a fixed text to the configured logging.

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|message|Message to be written to the log.
|===

== CommandExecutionAction

Executes a process and waits until the process has been completed. 

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|command|Process to be started. The process is started via System.Diagnostics.Process and should designate an executable file
|arguments|Arguments passed to the process
|workingDirectory|The working directory to which the process should switch. This is expanded by environment variables.
|===

== DocumentOpenAction

Opens the default program associated with a specific program.

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|filePath|File to be opened.
|===

== PowershellExecutionAction

Writes a script file and then executes it using Microsoft PowerShell.
The PowerShell instance used is the one accessible via the normal path variables. 

[%header,cols="1,5"]
|===
|Name|Description
|script|The script to be executed. 
|workingDirectory|The working directory to which the process should switch. This is expanded by environment variables.
|===


== LoadExtentAction

Executes a process and waits until the process has been completed. 

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|configuration|The extent configuration used for loading. 
|===
== DropExtentAction

Deletes an extent from the database.

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|workspace|Workspace from which the extent should be deleted.
|extentUri|Uri of the extent to be deleted.
|===

== CreateWorkspaceAction

Creates a new workspace.

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|workspace|Name of the workspace to be created.
|annotation|Description of the workspace
|===


== DropWorkspaceAction

Deletes a workspace from the database.

In addition to the properties of the _Action_ class, the following properties are supported

[%header,cols="1,5"]
|===
|Name|Description
|workspace|Workspace to be deleted from the database.
|===

== ClearCollectionAction

Deletes all elements of a collection. 
This can be an entire extent or a property of an object containing the collection. 


[%header,cols="1,5"]
|===
|Name|Description
|workspace|The workspace in which the object is found. Default is 'Data'
|path|The path pointing to a collection. This can be an extent or a property of an object 
|===

== CopyElementsAction

Copies all sub-elements from an object or extent to another extent. 

Derived from Action 

[%header,cols="1,5"]
|===
|Name|Description
|sourceWorkspace|The workspace in which the source elements are found
|targetWorkspace|The workspace to which the target elements are copied
|sourcePath|The path in the source workspace from which the elements are retrieved.
|targetPath|The path where the elements are copied. 
|===

=== Rules for Source Elements

- If the path to the source element is a ReflectiveCollection, all its elements are copied or moved. 
- If the path to the source element is an extent, all elements of the extent are copied or moved. 
- If the path to the source element is an object itself, only this object is copied or moved. 

=== Rules for Target Elements

- If the path to the target element is a ReflectiveCollection, all elements are copied or moved into it. 
- If the path to the target element is an extent, all elements are copied or moved into it. 
- If the path to the target element is an object itself, the elements are pushed into the standard property (usually 'packagedElement') of the element. 

== ExportToXmiAction

Takes a collection of objects, copies them into an Xmi extent, and exports the underlying XML file as XML.

[%header,cols="1,5"]
|===
|Name|Description
|sourceWorkspaceId|Defines the source workspace from which the data for the export is prepared. 
|sourcePath|Defines the source path used to find the data. 
|filePath|Path where the Xmi is exported.
|===

== ItemTransformationAction

Takes each individual object of the selected extent and passes it to the transformation object implementing the IItemTransformation interface. 

The selected object and all its sub-elements (recursively) are passed.

[%header,cols="1,5"]
|===
|Name|Description
|metaClass|An optional filter for the metaclasses to filter by. Only elements of these metaclasses are passed to the transformation. 
|runtimeClass|The full name of the .Net class instantiated to pass the selected objects to. This class can then perform the transformation. 
|workspace|Workspace in which the path is executed. 
|path|Uri, selecting the extent or the objects
|excludeDescendents|True if only the selected objects should be chosen and not the sub-objects underneath. 
|===

=== IItemTransformation Interface

This interface can be implemented by the implementations that are to perform the ItemTransformation according to the above description. 

It has the following method:

 void TransformItem(IElement element, IElement actionConfiguration);

* element: Describes the object being transformed. This is processed directly
* actionConfiguration: Extended configuration corresponding to the action instance itself. 

== SimpleReportAction

Generates a simple report. 

[%header,cols="1,5"]
|===
|Name|Description
|workspaceId|ID of the workspace 
|path|Path identifying the elements over which the report is generated.
|configuration|Configuration of the simple report of type 
SimpleReportConfiguration.
|filePath|File path where the report is stored. If no path is specified, a temporary file is created on the desktop. 
|===



