= Feldelement

Die DatenMeister Formulare unterstützen unterschiedliche Typen von Feldformularen. 
Dieses Kapitel enthält eine Beschreibung Dieser


== FieldData

Diese Basis-Klasse stellt die generischen Eigenschaften zur Verfügung, die von jedem Feld unterstützt werden sollten. 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|name|Name des Feldes und der dahinterliegenden Eigenschaft des Objektes
|title|Titel, der im Formular angezeigt wird
|isEnumeration|Flag, ob die Inhalte hinter der Eigenschafte eine Aufzählung sind oder ein einzelnes Element. Diese Eigenschaft wird von manchen Feldtypen zur automatischen Gestatung genutzt. 
|defaultValue|Falls der Wert nicht gesetzt ist, kann hier der Wert der Standard-Eigenschaft definiert werden. 
|isReadOnly|Flag, ob das Feld nicht beschreibbar ist. 
|===

== TextFieldData

Dieses Feld drückt ein Text-Eingabefeld aus in dem der Nutzer einen freien Text eintragen kann. 

Neben der Eigenschaften der FieldData werden noch folgende Eigenschaften unterstützt: 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|lineHeight|Anzahl der Zeilen, die angezeigt standardmäßig angezeigt werden sollen
|width|Breite in logischen Pixeln, die das Feld standardmäßig haben soll. 
|===


== EvalTextFieldData

Diese Erweiterung des Textfelds unterstützt die dynamische Auswertung von Inhalten. Dies ist im besonderen relevant bei der Report-Erstellung, da hier das Format und andere Eigenschaften dynamisch ausgewertet werden können. 

Neben der Eigenschaften der TextFieldData werden folgende Eigenschaften unterstützt:
[%header,cols="1,5"]
|===
|Name|Bedeutung
|evalCellProperties a|Das Skript, das zur Erstellung der Zelle ausgewertet wird. 

- Die Variable 'i' beschreibt das aktuell betrachtete Element 

- Die Variable 'c' die aktuelle Zelle. Die Eigenschaften des Zelle sind abhängig von verwendeten Report.

- Die Variable 'r' der Zustand der aktuellen Zeile, wie sie im ListForm in der Eigenschaft 'evalRowProperties' definiert werden kann. 
|===

== AnyDataFieldData

== CheckboxFieldData

== ActionFieldData

== DateTimeFieldData

== DropDownFieldData

== MetaClassElementFieldData

== ReferenceFieldData

== SubElementFieldData

Über dieses Feld-Element kann der Nutzer einer Eigenschaft mehrere Unterelemente zuordnen. 
Dieses Feld drücke eine 1:n Beziehung zwischen der Eigenschaft und dessen Unterelementen aus. 

Neben der Eigenschaften der FieldData werden folgende Eigenschaften unterstützt: 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|isEnumeration|Wird nicht ausgewertet
|isReadOnly|Flag, ob das Feld nicht beschreibbar ist. 
|form|Ein Listform, welches genutzt wird um das SubForm aufzubauen. Ist dieses leer, so wird die Metaklasse genutzt um das Formular aufzubauen. Ist auch 
die Metaklasse leer, so wird das Formular abhängig von den enthaltenen Eigenschaften erstellt. 
|defaultTypesForNewElements|Enthält eine Liste von Metaklassen, die genutzt wird um ein einfaches Erstellen von Items zu ermöglichen
|allowOnlyExistingElements|Wahr, wenn nur Referenzen auf bestehenden Elementen erzeugt werden können sollen. 
|===


== FileSelectionFieldData

== FileNameFieldData

== CheckboxListTaggingFieldData

== NumberFieldData