= Forms

== Requirements

=== GUI Application

The application has the following forms of representation:

The main window:

- In the main window, the user selects an extent, and all items therein should be displayed in a list. However, it can already be filtered by different views (e.g., by specific object types or special representations). Here, the input of the view is a collection of objects.
- In the main window, the user selects an element, and it should be displayed. In the first tab, the detail properties or the sub-elements can be displayed. Here too, filtering of elements or special representations can take place in further sub-windows. Here, the input of the view is a single object.

The detail window:

- If the user double-clicks on an item, a sub-window is opened. Several tabs can also be displayed here. This can be different from the previous use case. Here, the input of the view is a single object.

The control elements:

- If a property is displayed that can have several associated objects, a table is displayed. This table is not subdivided and does not consist of sub-tables. Here, the input of the view is an element and a property.

A form is required for the following elements:

- The elements of an extent ==> Listing of elements. Here, only lists of elements can be displayed, as there is no single object from which the property values can be queried.
- The object itself ==> The properties of the object are displayed.
- The elements of an object property ==> Here, an object and the property are passed. The individual elements are displayed via a list view.

With these requirements, the following design is chosen:

== Design

There are three types of main forms:

* Object Form: This form consists of several sub-forms and is designed for displaying a single item.
** This can be queried via an object or a metaclass.
* Collection Form: This form consists of several sub-forms and is designed for displaying a collection of elements.
** This can be queried via a collection of elements or an extent.
* Row Form: Here, each field is displayed in its own row.
** This can be queried via a metaclass.
* Table Form: Here, many elements are displayed in a table. These elements are defined in the context of the object to be displayed.
** This can be queried via a collection of objects, a metaclass, or a property of an object.

The ViewMode determines the context in which the object is displayed.


== Form

The form in general supports the following properties. All derivations must also support these properties.

[%header,cols="1,5"]
|===
|Name|Meaning
|name|Name of the form
|title|Title as it is displayed
|isReadOnly|Flag indicating whether the form is displayed in read-only mode
|hideMetaInformation|True if the meta-information of an object should not be automatically displayed in the form.
|originalUri|Since the form is cloned upon display, this property contains the URL before the cloning process.
|isAutoGenerated|Value indicating whether this form was automatically generated from object properties.
|creationProtocol|A debugging aid that explains how the form was created.
|===

== ObjectForm

An object form consists of several sub-forms and serves to display a single element. It is derived from Form.

Additional properties:

[%header,cols="1,5"]
|===
|Name|Meaning
|tab|A list of sub-forms
|autoTabs|Value indicating whether sub-forms should be automatically generated
|===


== ExtentForm

An extent form contains a set of forms to display a specific object.

The extent form is basically used in the main window when viewing the elements of an extent or when the user has selected a specific object in the main window.

=== Extent Form for Package
A special form is the list view of the package objects. Here, the user can determine via the 'preferredTypes' property which class instances can preferably be created in this package.

==== Implementation
The evaluation takes place in the FormsPlugin via FormsModificationPlugin, which contains a special set of rules here.

Various plugins can register here, which are allowed to change a form afterwards.

== ListForm
The list form describes a table or pure listing of a collection of objects:

[%header,cols="1,5"]
|===
|Name|Meaning
|property|n/a
|metaClass|n/a
|includeDescendents|n/a
|noItemsWithMetaClass|n/a
|inhibitNewItems|n/a
|inhibitDeleteItems|n/a
|defaultTypesForNewElements|n/a
|fastViewFilters|n/a
|duplicatePerType|Value indicating whether the list item should be duplicated for each type in the list. This property is used for ExtentForms so that the lists can be displayed per type.
|field|This list contains the fields that should be displayed in the list. Usually, these are the columns of the table.
|sortingOrder|The order in which the items should be displayed.
|viewNode|In this form, filtering or modification can be more specific via a data view. The actual list is passed as a dynamic data collection _input_.
|===



== FormModificationPlugins

The following FormModificationPlugins exist:

=== PackageFormModificationPlugin

Here, the following elements are added to the UML type 'Package' in the detail view:
- DefaultTypeForNewElement for creating buttons for generating new elements.

=== BasicNavigationForFormsAndItemsPlugin

Through this, as an IDatenMeisterPlugin, the following ActionButtons are added to the forms:

[%header,cols="1,1,5"]
|===
|Code|Name|Meaning
|Extent.NavigateTo|View Extent|Metaclass: Management.Extent
|Item.Delete|Delete Item|FormType: TreeItemDetail
|Item.New|New Item|FormType: TreeItemExtent, MetaClass: Management.Extent
|ExtentsList.ViewItem|View Item|FormType: TreeItemExtent
|ExtentsList.DeleteItem|Delete Item|FormType: TreeItemExtent
|===


include::datenmeister.forms.fields.adoc[leveloffset=+1]