= Aktionen und Aktionssammlungen

Über die Aktionen kann der Nutzer des Datenmeister eine Sequenz von Aktivitäten definieren, die im DatenMeister-Kontext ausführbar sind. 

Hierzu gibt es die beiden Basisklassen: 
. Action
. ActionSet

== ActionSet

Ein ActionSet (Aktionssammlung) sammelt verschiedene Aktionen. 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktionssammlung
|===
== Action

Die Basisklasse Action repräsentiert eine Aktion. Allerdings muss diese Klasse abgeleitet werden, damit die Aktion konkretisiert wird.


[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktion
|===

== LoggingWriterAction

Schreibt einen fixen Text in das konfigurierte Logging.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|message|Nachricht, die in das Log geschrieben werden soll.
|===

== CommandExecutionHandler

Führt einen Prozess aus und wartet bis der Prozess abgeschlossen worden ist. 

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|command|Prozess, der gestartet wird. Der Prozess wird über System.Diagnostics.Process gestartet und sollte eine ausführbare Datei bezeichnen
|arguments|Argumente, die dem Prozess mitgegeben werden
|===

== DropExtentAction

Löscht einen Extent aus der Datenbank.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Workspace aus dem der Extent gelöscht werden soll.
|extentUri|Uri des Extents welches gelöscht werden soll.
|===


== CreateWorkspaceAction

Erstellt einen neuen Workspace.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Name des Workspaces welcher erzeugt werden soll.
|annotation|Beschreibung des Workspaces
|===


== DropWorkspaceAction

Löscht einen Arbeitsbereich aus der Datenbank.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Workspace aus  der Datenbank gelöscht werden soll.
|===
