= Formulare

== Anforderungen

=== GUI-Applikation

In der Applikation gibt es folgende Darstellungsformen:

Das Hauptfenster:

- Im Hauptfenster wählt der Nutzer ein Extent und hierbei sollen alle Items in einer Liste angezeigt werden. Hierbei können allerdings schonnach verschiedenen Sichten gefiltert werden (zum Beispiel nach bestimmten Objekttypen oder spezielle Darstellungen). Hier ist der Eingang der Ansicht eine Sammlung von Objekten. 
- Im Hauptfenster wählt der Nutzer ein Element aus und dieses soll dargestellt werden. Im ersten Tab können die Detaileigenschaften oder auch die Unterelemente dargestellt werden. Auch hier können in weiteren Unterfenstern eine Filterung von Elementen oder besondere Darstellungen erfolgen. Hier ist der Eingang der Ansicht ein einzelnes Objekt.

Das Detailfenster:

- Klickt der Nutzer per Doppelklick auf ein Item, so wird ein Unterfenster geöffnet. Hier können auch mehrere Tabs dargestellt werden. Dieses kann unterschiedlich zum vorherigen Usecase sein. Hier ist der Eingang der Ansicht ein einzelnes Objekt.

Die Steuerelemente:

- Wird eine Eigenschaft angezeigt, die mehrere zugeordnete Objekte haben kann, so wird eine Tabelle angezeigt. Diese Tabelle ist nicht unterteilt und besteht nicht aus Untertabellen. Hier ist der Eingang der Ansicht ein Element und eine Eigenschaft. 

Ein Formular wird zu folgenden Elementen benötigt: 

- Die Elemente eines Extents ==> Auflistung von Elementen. Hierbei können nur Listen von Elementen angezeigt werden, da es nicht das einzelne Objekt gibt von welchem die Werte der Eigenschaften abgefragt werden können. 
- Das Objekt selbst ==> Die Eigenschaften des Objektes werden angezeigt.
- Die Elemente einer Objekteigenschaft  ==> Hierbei wird ein Objekt und die Eigenschaft übergeben. Über eine Listenansicht werden die einzelnen Elemente angezeigt.

Mit diesen Anforderungen wird für folgendes Design entschieden: 

== Design 

Es gibt drei Arten von Hauptformularen: 

* Object Form: Dieses Formular besitzt mehrere Unterformulare und ist zur Darstellung eines einzelnen Items ausgelegt. 
** Dieses kann über ein Objekt oder eine Metaklasse abgefragt werden. 
* Collection Form: Dieses Formular bestitzt mehrere Unterformulare und ist zur Darstellung einer Sammlung von Elementen ausgelegt. 
** Dieses kann über eine Sammlung von Elementen oder ein Extent abgefragt werden. 
* Row Form: Hier werden jedes Feld in einer eigenen Zeile dargestellt. 
** Dieses kann über eine Metaklasse abgefragt werden. 
* Table Form: Hier werden viele Elemente in einer Tabelle angezeigt. Diese Elemente werden im Kontext des darzustellenden Objektes definiert.
** Dieses kann über eine Sammlung von Objekten, eine Metaklasse oder einer Eigenschaft eines Objektes abgefragt werden.  

Über den ViewMode wird festgelegt in welchem Kontext das Objekt angezeigt wird.


== Form

Das Formular im Allgemeinen unterstützt folgende Eigenschaften. Alle Ableitungen haben auch diese Eigenschaften zu unterstützen. 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|name|Name des Formulars
|title|Titel, wie er angezeigt wird
|isReadOnly|Flag, ob das Formular im schreibgeschützten Modus angezeigt wird
|hideMetaInformation|Wahr, wenn im Formular nicht automatisch die Meta-Informationen eines Objektes angezeigt werden soll. 
|originalUri|Da das Formular bei der Anzeige geklont wird, enthält diese Eigenschaft die Url vor dem Klonvorgang. 
|isAutoGenerated|Wert, ob dieses Formular automatisch aus Objekt-Eigenschaften generiert worden ist. 
|creationProtocol|Eine Debugging-Hilfe, die darlegt, wie das Formular erstellt worden ist. 
|===

== ObjectForm

Ein Objekt-Form besteht aus mehreren Unterformularen und dient zur Anzeige eines einzelnen Elements. Es ist von Form abgeleitet.

Weitere Eigenschaften:

[%header,cols="1,5"]
|===
|Name|Bedeutung
|tab|Eine Auflistung der Unterformulare
|autoTabs|Wert, ob Unterformulare automatisch generiert werden sollen
|===


== ExtentForm

Ein Extent Form ist enthält einen Satz von Formularen um ein konkretes Objekt anzuzeigen. 

Das Extent Form wird prinzipiell im Hauptfenster bei der Ansicht der Elemente eines Extents genutzt oder auch wenn der Nutzer im Hauptfenster ein konkretes Objekt ausgewählt hat. 

=== Extent Form für Package
Ein besonderes Formular ist die Listenansicht der Package-Objekte. Hier kann der Nutzer über die 'Eigenschaft' der preferredTypes festlegen, welche Klasseninstanzen bevorzugt in diesem Package angelegt werden können. 

==== Implementierung
Die Evaluierung erfolg im FormsPlugin per FormsModificationPlugin, welcher hier ein besonderes Regelwerk enthält. 

Es können sich hier verschiedene Plugins registrieren, die nachträglich nochmals ein Formular verändern dürfen. 

== ListForm
Das Listenformular beschreibt eine Tabelle bzw. reine Auflistung einer Sammlung von Objekten: 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|property|k.A.
|metaClass|k.A.
|includeDescendents|k.A.
|noItemsWithMetaClass|k.A.
|inhibitNewItems|k.A.
|inhibitDeleteItems|k.A.
|defaultTypesForNewElements|k.A.
|fastViewFilters|k.A.
|duplicatePerType|Wert, ob das Listenitem für jeden Typ in der Liste dupliziert werden soll. Diese Eigenschaft wird für die ExtentForms genutzt, damit man die Listen pro Typ anzeigen kann. 
|field|Diese Auflistung enthält die Felder, die in der Liste angezeigt werden sollen. Üblicherweise sind dies die Spalten der Tabelle
|sortingOrder|Die Reihenfolge in der die Items angezeigt werden sollen.
|viewNode|In diesem Formular kann nochmals konkreter über eine Datenansicht gefiltert oder verändert werden. Die eigentliche Liste wird als dynamische Datensammlung _input_ übergeben. 
|===



== FormModificationPlugins

Folgende FormModificationPlugins gibt es: 

=== PackageFormModificationPlugin

Hier werden dem UML-Type 'Package' in der Detailansicht folgende Elemente hinzugefügt: 
- DefaultTypeForNewElement zur Erstellung der Buttons für die Erzeugung neuer Elemente

=== BasicNavigationForFormsAndItemsPlugin

Hierüber werden als IDatenMeisterPlugin folgende ActionButtons den Formularen hinzugefügt: 

[%header,cols="1,1,5"]
|===
|Code|Name|Bedeutung
|Extent.NavigateTo|View Extent|Metaclass: Management.Extent
|Item.Delete|Delete Item|FormType: TreeItemDetail
|Item.New|New Item|FormType: TreeItemExtent, MetaClass: Management.Extent
|ExtentsList.ViewItem|View Item|FormType: TreeItemExtent
|ExtentsList.DeleteItem|Delete Item|FormType: TreeItemExtent
|===


include::datenmeister.forms.fields.adoc[leveloffset=+1]