= Formulare

Es gibt drei Arten von Hauptformularen: 

* Detail-Formular
* Listen-Formular
* Extent-Formular (eigentlich sollte es Objekt-Formular heißen)

== Form

Das Formular im Allgemeinen unterstützt folgende Eigenschaften. Alle Ableitungen haben auch diese Eigenschaften zu unterstützen. 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|name|Name des Formulars
|title|Titel, wie er angezeigt wird
|isReadOnly|Flag, ob das Formular im schreibgeschützten Modus angezeigt wird
|hideMetaInformation|Wahr, wenn im Formular nicht automatisch die Meta-Informationen eines Objektes angezeigt werden soll. 
|originalUri|Da das Formular bei der Anzeige geklont wird, enthält diese Eigenschaft die Url vor dem Klonvorgang. 
|===

== ExtentForm

Ein Extent Form ist enthält einen Satz von Formularen um ein konkretes Objekt anzuzeigen. 

Das Extent Form wird prinzipiell im Hauptfenster bei der Ansicht der Elemente eines Extents genutzt oder auch wenn der Nutzer im Hauptfenster ein konkretes Objekt ausgewählt hat. 


=== Extent Form für Package
Ein besonderes Formular ist die Listenansicht der Package-Objekte. Hier kann der Nutzer über die 'Eigenschaft' der preferredTypes festlegen, welche Klasseninstanzen bevorzugt in diesem Package angelegt werden können. 

==== Implementierung
Die Evaluierung erfolg im FormsPlugin per FormsModificationPlugin, welcher hier ein besonderes Regelwerk enthält. 

Es können sich hier verschiedene Plugins registrieren, die nachträglich nochmals ein Formular verändern dürfen. 

== ListForm
Das Listenformular beschreibt eine Tabelle bzw. reine Auflistung einer Sammlung von Objekten: 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|property|k.A.
|metaClass|k.A.
|includeDescendents|k.A.
|noItemsWithMetaClass|k.A.
|inhibitNewItems|k.A.
|inhibitDeleteItems|k.A.
|defaultTypesForNewElements|k.A.
|fastViewFilters|k.A.
|duplicatePerType|Wert, ob das Listenitem für jeden Typ in der Liste dupliziert werden soll. Diese Eigenschaft wird für die ExtentForms genutzt, damit man die Listen pro Typ anzeigen kann. 
|field|Diese Auflistung enthält die Felder, die in der Liste angezeigt werden sollen. Üblicherweise sind dies die Spalten der Tabelle
|sortingOrder|Die Reihenfolge in der die Items angezeigt werden sollen.
|viewNode|In diesem Formular kann nochmals konkreter über eine Datenansicht gefiltert oder verändert werden. Die eigentliche Liste wird als dynamische Datensammlung _input_ übergeben. 
|===


== Feld-Typen

Jedes Formular besteht aus einer Sammlung von Feldern. Hier werden folgende Felder unterstützt

=== FieldData

Diese Basis-Klasse stellt die generischen Eigenschaften zur Verfügung, die von jedem Feld unterstützt werden sollten. 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|name|Name des Feldes und der dahinterliegenden Eigenschaft des Objektes
|title|Titel, der im Formular angezeigt wird
|isEnumeration|Flag, ob die Inhalte hinter der Eigenschafte eine Aufzählung sind oder ein einzelnes Element. Diese Eigenschaft wird von manchen Feldtypen zur automatischen Gestatung genutzt. 
|defaultValue|Falls der Wert nicht gesetzt ist, kann hier der Wert der Standard-Eigenschaft definiert werden. 
|isReadOnly|Flag, ob das Feld nicht beschreibbar ist. 
|===

=== TextFieldData

Dieses Feld drückt ein Text-Eingabefeld aus in dem der Nutzer einen freien Text eintragen kann. 

Neben der Eigenschaften der FieldData werden noch folgende Eigenschaften unterstützt: 

[%header,cols="1,5"]
|===
|Name|Bedeutung
|lineHeight|Anzahl der Zeilen, die angezeigt standardmäßig angezeigt werden sollen
|width|Breite in logischen Pixeln, die das Feld standardmäßig haben soll. 
|===


=== EvalTextFieldData

Diese Erweiterung des Textfelds unterstützt die dynamische Auswertung von Inhalten. Dies ist im besonderen relevant bei der Report-Erstellung, da hier das Format und andere Eigenschaften dynamisch ausgewertet werden können. 

Nebenn der Eigenschaften der TextFieldData werden folgende Eigenschaften unterstützt:
[%header,cols="1,5"]
|===
|Name|Bedeutung
|evalCellProperties a|Das Skript, das zur Erstellung der Zelle ausgewertet wird. 

- Die Variable 'i' beschreibt das aktuell betrachtete Element 

- Die Variable 'c' die aktuelle Zelle. Die Eigenschaften des Zelle sind abhängig von verwendeten Report.

- Die Variable 'r' der Zustand der aktuellen Zeile, wie sie im ListForm in der Eigenschaft 'evalRowProperties' definiert werden kann. 
|===