= Aktionen und Aktionssammlungen

Über die Aktionen kann der Nutzer des Datenmeister eine Sequenz von Aktivitäten definieren, die im DatenMeister-Kontext ausführbar sind. 

Hierzu gibt es die beiden Basisklassen: 
. Action
. ActionSet

== ActionSet

Ein ActionSet (Aktionssammlung) sammelt verschiedene Aktionen. 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktionssammlung
|===
== Action

Die Basisklasse Action repräsentiert eine Aktion. Allerdings muss diese Klasse abgeleitet werden, damit die Aktion konkretisiert wird.


[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktion
|===

== LoggingWriterAction

Schreibt einen fixen Text in das konfigurierte Logging.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|message|Nachricht, die in das Log geschrieben werden soll.
|===

== CommandExecutionAction

Führt einen Prozess aus und wartet bis der Prozess abgeschlossen worden ist. 

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|command|Prozess, der gestartet wird. Der Prozess wird über System.Diagnostics.Process gestartet und sollte eine ausführbare Datei bezeichnen
|arguments|Argumente, die dem Prozess mitgegeben werden
|workingDirectory|Das Arbeitsverzeichnis zu dem der Prozess wechseln soll. Dieser wird um die Umgebungsvariablen erweitert.
|===



== PowershellExecutionAction

Schreibt eine Skript-Datei und führt diese dann mit Hilfe von Microsoft Powershell aus.
Hierbei wird die Powershell-Instanz genutzt, welche über die normale Pfad-Variablen aufrufbar sind. 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|script|Das Skript, welches ausgeführt wird. 
|workingDirectory|Das Arbeitsverzeichnis zu dem der Prozess wechseln soll. Dieser wird um die Umgebungsvariablen erweitert.
|===


== LoadExtentAction

Führt einen Prozess aus und wartet bis der Prozess abgeschlossen worden ist. 

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|configuration|Die Extent-Konfiguration, die zum Laden genutzt wird. 
|===
== DropExtentAction

Löscht einen Extent aus der Datenbank.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Workspace aus dem der Extent gelöscht werden soll.
|extentUri|Uri des Extents welches gelöscht werden soll.
|===


== CreateWorkspaceAction

Erstellt einen neuen Workspace.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Name des Workspaces welcher erzeugt werden soll.
|annotation|Beschreibung des Workspaces
|===


== DropWorkspaceAction

Löscht einen Arbeitsbereich aus der Datenbank.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Workspace aus  der Datenbank gelöscht werden soll.
|===

== CopyElementsAction

Kopiert alle Unterelemente von einem Objekt oder Extent zu einem anderen Extent. 

Abgeleitet von Action 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|sourceWorkspace|Der Arbeitsbereich in dem die Quell-Elemente gefunden werden
|targetWorkspace|Der Arbeitsbereich zu dem die Ziel-Elemente kopiert werden
|sourcePath|Der Pfad in dem Quell-Arbeitsbereich aus dem die Elemente geholt werden.
|targetPath|Der Pfad in dem die Elemente kopiert werden. 
|===

=== Regeln für Quell-Elemente

- Wenn der Pfad zum Quell-Element eine ReflectiveCollection ist, werden alle Elemente dieser kopiert oder verschoben. 
- Wenn der Pfad zum Quell-Element ein Extent ist, werden alle Elemente des Extents kopiert oder verschoben. 
- Wenn der Pfad zum Quell-Element ein Objekt selbst ist, wird nur dieses kopiert oder verschoben. 

=== Regeln für Ziel-Elemente

- Wenn der Pfad zum Ziel-Element eine ReflectiveCollection ist, werden alle Elemente in diese kopiert oder verschoben. 
- Wenn der Pfad zum Ziel-Element ein Extent ist, werden alle Elemente in diese kopiert oder verschoben. 
- Wenn der Pfad zum Ziel-Element ein Objekt selbst ist, werden die Elemente in die Standard-Eigenschaft (meist 'packagedElement') des Elements geschoben. 

== ExportToXmiAction

Nimmt eine Sammlung von Objekten, kopiert diese in einen Xmi-Extent und exportiert die dahinterliegende Xml-Datei als Xml.

[%header,cols="1,5"]
|===
|Name|Beschreibung
|sourceWorkspaceId|Definiert den Quell-Arbeitsbereich aus dem die Daten für den Export vorbereitet werden. 
|sourcePath|Definiert den Quell-Pfad der zum Auffinden der Daten genutzt wird. 
|filePath|Pfad in dem das Xmi exportiert wird.
|===