= Öffentliche Einstellungen

Die öffentlichen Einstellungen (PublicSettings) wird über die Datei 'DatenMeister.Settings.xmi' konfiguriert, die im Verzeichnis der ausführbaren Datei (.exe) liegen muss. 

Diese Datei ist eine Xmi-Datei mit einem settings-Knoten und sieht beispielhaft folgendermaßen aus: 

 <xmi>
     <settings
 		windowTitle = "The IssueMeister" 
         databasePath="%LOCALAPPDATA%/IssueMeister">
         <environnemtVariable key="import_path" value="c:\import-folder" />
     </settings>
 </xmi>

Folgende Eigenschaften werden unterstützt: 

[%header,cols="1,5"]
|===
|Name|Eigenschaft
|windowTitle|Name des Hauptfensters. Standardmäßig 'DatenMeister'
|databasePath|Pfad in dem die Hauptkonfiguration gespeichert wird. Dies sind üblicherweise die benutzerdefinierten Typen und Formulare, aber auch die Registrierung von Workspaces und Arbeitsbereichen
|isReadOnly|Flag, ob der DatenMeister im Read-Only Modus gestartet werden soll
|logLocation a|Definiert an welcher Stelle das Logging durchgeführt werden soll. 

* Application: Im Applikationsverzeichnis (Standard)
* LocalAppData: Im Unterverzeichnis 'DatenMeister' der LocalAppData
* Desktop: Direkt auf dem Desktop
* None: Es findet kein Logging in einer Datei statt. 
|environmentVariable a|Weitere Umgebungsvariablen können hier eingefügt werden. Diese werden ohne Präfix direkt in die Umgebungsvariablen des Prozesses eingefügt. 

Es können mehrer Umgebungsvariablen angegeben werden, die folgende Eigenschaften haben können: 

* key: Name der Variable
* value: Wert der Variablen
|===

== Umgebungsvariablen

Beim Einladen der öffentlichen Einstellungen wird der Datenbankpfad in die Umgebungsvariable "dm_databasepath" übertragen und ist damit für das Einladen der Extents verfügbar. 

Weiterhin werden die Umgebungsvariablen gemäß der Eigenschaften der 'environmentVariable' übertragen. 