= Modellierer

== Evaluierte Texte

Der DatenMeister bietet neben der statischen Zuordnung von Inhalten von Objekteigenschaften zu Texten auch eine Möglichkeit diese Eigenschaften mit Hilfe des https://github.com/lunet-io/scriban[Scriban] Frame-Works zu evaluieren und so dynamischer die Inhalte der Objekte darstellen. 

Das Scriban-Objekt {{i}} enthält das aktuelle Element, welche bearbeitet wird. Ist das aktuelle Objekt eine Person, so erhält man über "{{i.name}}"" den Namen der Person zurück. Über "Hallo {{i.prename}} {{i.name}}" begrüßt man ihn. 

Das Präfix <% ist reserviert, um zukünftige Alternativen Evaluierer zu unterstützen. 

Typischerweise kann die Evaluierung eines Texts über die Eigenschaft 'eval{Property}' gesteuert werden, wobei Property der Name der Eigenschaft ist, die üblicherweise die statische Zuordnung zwischen anzuzeigenden Inhalt und Objekt-Eigenschaft festlegt. 

== Formulare

Es gibt drei Arten von Hauptformularen: 

* Detail-Formular
* Listen-Formular
* Extent-Formular (eigentlich sollte es Objekt-Formular heißen)

=== ExtentForm

Ein Extent Form ist enthält einen Satz von Formularen um ein konkretes Objekt anzuzeigen. 

Das Extent Form wird prinzipiell im Hauptfenster bei der Ansicht der Elemente eines Extents genutzt oder auch wenn der Nutzer im Hauptfenster ein konkretes Objekt ausgewählt hat. 


==== Package Form
Ein besonderes Formular ist die Listenansicht der Package-Objekte. Hier kann der Nutzer über die 'Eigenschaft' der preferredTypes festlegen, welche Klasseninstanzen bevorzugt in diesem Package angelegt werden können. 

===== Implementierung
Die Evaluierung erfolg im FormsPlugin per FormsModificationPlugin, welcher hier ein besonderes Regelwerk enthält. 

Es können sich hier verschiedene Plugins registrieren, die nachträglich nochmals ein Formular verändern dürfen. 


== DataViews

Über Datenansichten erhält der Modellierer und Nutzer Zugriff auf Sammlungen von Objekten oder Instanzen von Objekten. 

Die Datenansichten sind im Namespace _DatenMeister.Models.Namespace_ definiert. 

Eine Datenansicht referenziert einen Ansichtsknoten (ViewNode), der eines oder mehrere Objekte zurückgibt. Dieser Knoten können miteinander verkettet werden, damit auch komplexe Datenaggregationen möglich sind. 