= Aktionen und Aktionssammlungen

Über die Aktionen kann der Nutzer des Datenmeister eine Sequenz von Aktivitäten definieren, die im DatenMeister-Kontext ausführbar sind. 

Hierzu gibt es die beiden Basisklassen: 
. Action
. ActionSet

Jede Aktion hat folgende Eigenschaften:

[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktion
|isDisabled|Flag, ob die Aktion deaktiviert ist und damit in der Aktionssammlung übersprungen wird. 
|===

== ActionSet

Ein ActionSet (Aktionssammlung) sammelt verschiedene Aktionen. 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktionssammlung
|===
== Action

Die Basisklasse Action repräsentiert eine Aktion. Allerdings muss diese Klasse abgeleitet werden, damit die Aktion konkretisiert wird.


[%header,cols="1,5"]
|===
|Name|Beschreibung
|name|Name der Aktion
|===

== LoggingWriterAction

Schreibt einen fixen Text in das konfigurierte Logging.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|message|Nachricht, die in das Log geschrieben werden soll.
|===

== CommandExecutionAction

Führt einen Prozess aus und wartet bis der Prozess abgeschlossen worden ist. 

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|command|Prozess, der gestartet wird. Der Prozess wird über System.Diagnostics.Process gestartet und sollte eine ausführbare Datei bezeichnen
|arguments|Argumente, die dem Prozess mitgegeben werden
|workingDirectory|Das Arbeitsverzeichnis zu dem der Prozess wechseln soll. Dieser wird um die Umgebungsvariablen erweitert.
|===



== PowershellExecutionAction

Schreibt eine Skript-Datei und führt diese dann mit Hilfe von Microsoft Powershell aus.
Hierbei wird die Powershell-Instanz genutzt, welche über die normale Pfad-Variablen aufrufbar sind. 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|script|Das Skript, welches ausgeführt wird. 
|workingDirectory|Das Arbeitsverzeichnis zu dem der Prozess wechseln soll. Dieser wird um die Umgebungsvariablen erweitert.
|===


== LoadExtentAction

Führt einen Prozess aus und wartet bis der Prozess abgeschlossen worden ist. 

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|configuration|Die Extent-Konfiguration, die zum Laden genutzt wird. 
|===
== DropExtentAction

Löscht einen Extent aus der Datenbank.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Workspace aus dem der Extent gelöscht werden soll.
|extentUri|Uri des Extents welches gelöscht werden soll.
|===

== CreateWorkspaceAction

Erstellt einen neuen Workspace.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Name des Workspaces welcher erzeugt werden soll.
|annotation|Beschreibung des Workspaces
|===


== DropWorkspaceAction

Löscht einen Arbeitsbereich aus der Datenbank.

Neben der Eigenschaften der Klasse _Action_ werden folgende Eigenschaften unterstützt

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Workspace aus  der Datenbank gelöscht werden soll.
|===

== ClearCollectionAction

Löscht alle Elemente einer Sammlung. 
Dies kann ein komplettes Extent sein oder auch die Eigenschaft eines Objektes welches die Sammlung enthält. 


[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspace|Der Arbeitsbereich in dem das Objekt gefunden wird. Standard ist 'Data'
|path|Der Pfad, der auf eine Sammlung verweist. Dies kann ein Extent oder eine Eigenschaft eines Objektes sein 
|===

== CopyElementsAction

Kopiert alle Unterelemente von einem Objekt oder Extent zu einem anderen Extent. 

Abgeleitet von Action 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|sourceWorkspace|Der Arbeitsbereich in dem die Quell-Elemente gefunden werden
|targetWorkspace|Der Arbeitsbereich zu dem die Ziel-Elemente kopiert werden
|sourcePath|Der Pfad in dem Quell-Arbeitsbereich aus dem die Elemente geholt werden.
|targetPath|Der Pfad in dem die Elemente kopiert werden. 
|===

=== Regeln für Quell-Elemente

- Wenn der Pfad zum Quell-Element eine ReflectiveCollection ist, werden alle Elemente dieser kopiert oder verschoben. 
- Wenn der Pfad zum Quell-Element ein Extent ist, werden alle Elemente des Extents kopiert oder verschoben. 
- Wenn der Pfad zum Quell-Element ein Objekt selbst ist, wird nur dieses kopiert oder verschoben. 

=== Regeln für Ziel-Elemente

- Wenn der Pfad zum Ziel-Element eine ReflectiveCollection ist, werden alle Elemente in diese kopiert oder verschoben. 
- Wenn der Pfad zum Ziel-Element ein Extent ist, werden alle Elemente in diese kopiert oder verschoben. 
- Wenn der Pfad zum Ziel-Element ein Objekt selbst ist, werden die Elemente in die Standard-Eigenschaft (meist 'packagedElement') des Elements geschoben. 

== ExportToXmiAction

Nimmt eine Sammlung von Objekten, kopiert diese in einen Xmi-Extent und exportiert die dahinterliegende Xml-Datei als Xml.

[%header,cols="1,5"]
|===
|Name|Beschreibung
|sourceWorkspaceId|Definiert den Quell-Arbeitsbereich aus dem die Daten für den Export vorbereitet werden. 
|sourcePath|Definiert den Quell-Pfad der zum Auffinden der Daten genutzt wird. 
|filePath|Pfad in dem das Xmi exportiert wird.
|===

== ItemTransformationAction

Nimmt jedes einzelne Objekt des gewählten Extents und übergibt es dem Transformationsobjekt welche die Schnittstelle IItemTransformation implementiert. 

Das gewählte Objekt und all seine Unterelemente (rekursiv) werden übergeben.

[%header,cols="1,5"]
|===
|Name|Beschreibung
|metaClass|Ein optionaler Filter auf die Meta-Klassen auf die gefiltert werden kann. Nur Elemente dieser Metaklassen werden der Transformation übergeben. 
|runtimeClass|Der volle Name der .Net Klasse, die instanziiert wird um die gewählten Objekten dieser zu übergeben. Diese Klassen kann dann die Transformation vornehmen. 
|workspace|Arbeitsbereich in dem der Pfad ausgeführt wird. 
|path|Uri, die das Extent oder die Objekte selektiert
|excludeDescendents|True, falls nur die selektierten Objekte gewählt werden sollen und nicht die darunterliegenden Unterobjekte. 
|===

=== Schnittstelle IItemTransformation

Diese Schnittstelle kann von den Implementierungen umgesetzt werden, die die ItemTransformation gemäß obiger Darstellung durchführen soll. 

Diese besitzt folgende Methode

 void TransformItem(IElement element, IElement actionConfiguration);

* element: Beschreibt das Objekt welches transformiert wird. Dieses wird direkt bearbeitet
* actionConfiguration: Erweiterte Konfiguration, die der Action-Instanz selbst entspricht. 

= SimpleReportAction

Erzeugt einen einfachen Bericht. 

[%header,cols="1,5"]
|===
|Name|Beschreibung
|workspaceId|Id des Arbeitsbereiches 
|path|Pfad der die Elemente identifiziert über die der Report erzeugt wird.
|configuration|Konfiguration es einfachen Berichtes vom Typ 
SimpleReportConfiguration.
|filePath|Dateipfad in dem der Report abgelegt wird. Ist kein Pfad angegeben, so wird eine temporäre Datei auf dem Desktop erzeugt. 
|===



