= SW-API

== DatenMeister.dll

=== Module Runtime.ExtentStorage

Prinzipiell ist der DatenMeister in der Lage mit entkoppelten Extents zu arbeiten. Dies bedeutet, dass man Extents laden kann, die ohne zentralisierte Registrierung genutzt, bearbeitet und wieder gespeichert werden können. 

Der DatenMeister unterstützt aber parallel eine zentrale Registrierung über den *ExtentManager*, welcher das Laden, das Sperren und das abgesicherte Abspeichern bei Beendigung der Applikation unterstützt. 

Es gibt damit insgesamt zwei Datenbanken in den die Extents gespeichert werden. 

. Innerhalb der Workspaces (_WorkspaceLogic.GetWorkspaces()_) sind die Extents eingefügt. Hierüber können Extents im normalen Datenbankprinzip gefunden werden. Hier ist aber nicht bekannt über welchen ProviderLoader das Extent von welcher Quelle geladen worden ist. 

. Über die Registrierung des ExtentManager (_ExtentStorageData_) werden geladene Extents zum Zwecke der Nachverfolgung bein Locking und Speichern gespeichert. Der ExtentManager weist auch die genutzter ProviderLoader Config dem Extent zu. 

Folgende Methoden werden bei der Verwendung von Extents genutzt: 

* Beim Einladen über _LoadExtent_ wird das Extent eingeladen und registriert. Beim Einladen wird das Extent über seinen Provider auch gesperrt.

* Beim Entladen über _DetachExtent_ wird das Extent deregistriert, aber nicht gespeichert. Das Extent wird über seinen Provider auch wieder entsperrt. 

* Über _LoadAllExtents_ findet das Einladen der ExtentLoaderConfig statt, die von der vorherigen Instanz speichert, welche Extents beim Hochfahren einzuladen sind. Das Einladen erfolgt dann auch über _LoadExtent_ und führt damit zu einer Sperrung der Extents. 

* Über _StoreAllExtents_ findet ein Write Trigger über alle geladenen und registrierten Events statt. 

* Über _DeleteExtent_ wird das Extent nicht nur aus der Registrierung entfernt, sondern auch aus dem Workspace genommen. 

* Über _UnloadManager_ werden die Extents entladen und der Zugriff auf die Registrierungs-Datei komplett aufgehoben. Die Extents selbst sind noch in den Workspaces, werden aber nicht mehr über den ExtentManager nachverfolgt. 


== Module.Reports

Die Generierung von Reports wird von zwei Report Generatoren unterstützt: 

* SimpleReport
* TextReport

=== Simple Report

Implementiert in den Klassen _SimpleReportConfiguration_ und _SimpleReportCreator_

=== Text Report
