:doctype: book
:toc: left
:toclevels: 4
:listing-caption: Listing

= Das Wissen

== Was soll denn dieses Buch? 

Dieses Buch sammelt verschieden Ideen, Aspekte und Themen resultierend aus meiner täglichen Arbeit im Büro und Gedanken von zu Hause. Dieses Buch enthält natürlich keine konkreten Interna meines Arbeitgebers oder identifizierbare Anekdoten. 

Fokussiert wird sich hier auf das Systems Engineering, die Modellierung von Elemeenten, Schnittstellen und Eigenschaften komplexer Systeme. Zerlegung ist die Kunst. Hierbei betrachten wir auch die großen Standards wie UML, SysML and MOF. Weiterhin gibt es hier Anforderungen, Architektur, Aufgaben, Projektmanagement und anderer bekloppeter Dinger. 

Das komplette Buch ist zur besseren Verständlichkeit in deutsch geschrieben. Erreiche ich nicht das weltweite Publikum besser? Darüber habe ich lange nachgedacht, aber mich aus folgenden Gründen doch für die deutsche Sprache entschieden: 

* Ich schreibe eleganter und effizienter
* Die Erläuterungen sind plastischer und besser verständlich
* Es gibt ausreichend gute Übersetzungsmaschinen

Die Quelle des Buchs ist verfügbar unter https://github.com/mbrenn/theknowledge[Github] und Pull Requests sind immer willkommen. 

== Weitere Kapitel

* link:datenmeister/datenmeister.html[DatenMeister]
* link:Systems%20Engineering/systemengineering.html[Systems Engineering]
* link:Tools/cooletools.html[Toolings]
* link:Trainings/training.html[Trainings / Cheatsheets]
