= Alkoholfreie Bier

Anbei ein Rating verschiedener alkoholfreier Biere... Welche mag ich, welche mag ich nicht...

https://www.xn--mnchshof-n4a.de/brauspezialitaeten/naturtruebs-alkoholfrei.html9[Mönchshof - Original Naturtrüb's Alkoholfrei]:: Getrunken habe ich es gut gekühlt. 6/10 Punkte
+
Gibt es in einer 0,5er Ploppflasche. Den Plopp-Test hat das Bier gut überstanden, es ploppt. Ausreichen Kohlensäure, schmeckt ein wenig dünn und verstopft nicht den Geschmack... Der Alkohol fehlt. Vom Geschmack her ist das Bier bierig, schmeckt beim Abgang nur leicht süßlich und eine Malznote findet sich, bei herbigem Grundgeschmack. Nach dem Genuss einer vollen Flasche habe ich spontan keine Lust auf ein zweites Bier. 

https://www.andechs.de/klosterbrauerei/sortiment/weissbier-alkoholfrei.html[Kloster Andechs Alkoholfrei]:: Ein Fest! 8/10 Punkte
+
Bereits der zweite Kasten am Stück gekauft und schmeckt nach täglichem Genuss. Wunderbar, wunderbar, wunderbar... Ein Fest... Schmeckt herb und der 'typisch' alkoholfrei-süßliche Geschmack ist mit einer feinen Noten schmeckbar, aber prägt nicht den Gesamtgeschmack, genau richtig. Kohlensäure ist mir ein Ticken zuviel, aber das lässt sich mit der entsprechenden Einschenk-Technik kompensieren. Kostet einen Euro mehr pro Kasten, aber uneingeschränkt empfehlbar. 